# Generated by Django 5.1.3 on 2025-09-27 04:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial_squashed_0005_remove_course_courses_is_acti_25e634_idx_and_more'),
        ('tests', '0004_testregistration_attempted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField()),
                ('payment_method', models.CharField(choices=[('card', 'card'), ('kakaopay', 'kakaopay'), ('naverpay', 'naverpay'), ('tosspay', 'tosspay'), ('bank_transfer', 'bank_transfer')], db_index=True, max_length=30)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('cancelled', 'cancelled'), ('failed', 'failed'), ('refunded', 'refunded')], db_index=True, default='paid', max_length=20)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course_registration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='courses.courseregistration')),
                ('test_registration', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='tests.testregistration')),
            ],
            options={
                'db_table': 'payments',
                'indexes': [models.Index(fields=['created_at'], name='payments_created_e3a130_idx'), models.Index(fields=['status'], name='payments_status_d621e5_idx'), models.Index(fields=['payment_method'], name='payments_payment_ee488d_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('course_registration__isnull', False), ('test_registration__isnull', True)), models.Q(('course_registration__isnull', True), ('test_registration__isnull', False)), _connector='OR'), name='payment_exactly_one_target'), models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_gt_0')],
            },
        ),
    ]
