# Generated by Django 5.1.3 on 2025-09-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial_squashed_0005_remove_course_courses_is_acti_25e634_idx_and_more'),
        ('payments', '0001_initial'),
        ('tests', '0006_alter_test_registrations_count'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='payment',
            name='payments_payment_ee488d_idx',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'card'), ('kakaopay', 'kakaopay'), ('naverpay', 'naverpay'), ('tosspay', 'tosspay'), ('bank_transfer', 'bank_transfer')], max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('paid', 'paid'), ('cancelled', 'cancelled'), ('failed', 'failed'), ('refunded', 'refunded')], default='paid', max_length=20),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(condition=models.Q(('status', 'paid')), fields=['paid_at'], name='payments_paid_at_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(condition=models.Q(('status__in', ['cancelled', 'refunded'])), fields=['canceled_at'], name='payments_canceled_at_idx'),
        ),
    ]
