services:
  db:
    image: postgres:15
    container_name: database
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-examdb}
      POSTGRES_USER: ${POSTGRES_USER:-examuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-exam-pass}
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-examuser} -d ${POSTGRES_DB:-examdb}"]
      interval: 5s
      timeout: 3s
      retries: 10

  server:
    build: .
    container_name: server
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app