# Generated by Django 5.1.3 on 2025-09-28 05:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registrations_count', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'db_table': 'courses',
                'indexes': [models.Index(fields=['created_at'], name='courses_created_0aa93c_idx'), models.Index(fields=['is_active'], name='courses_is_acti_25e634_idx')],
            },
        ),
        migrations.CreateModel(
            name='CourseRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('registered', 'registered'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('cancelled', 'cancelled')], db_index=True, default='registered', max_length=20)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='courses.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'course_registrations',
                'indexes': [models.Index(fields=['course'], name='course_regi_course__c6f073_idx'), models.Index(fields=['user'], name='course_regi_user_id_0f4020_idx'), models.Index(fields=['status'], name='course_regi_status_aa3ec7_idx')],
                'unique_together': {('user', 'course')},
            },
        ),
        migrations.RemoveIndex(
            model_name='course',
            name='courses_is_acti_25e634_idx',
        ),
        migrations.AlterField(
            model_name='course',
            name='registrations_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['registrations_count'], name='courses_registr_027083_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active', 'start_at', 'end_at'], name='courses_is_acti_2b8793_idx'),
        ),
    ]
