# Generated by Django 5.1.3 on 2025-09-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_rollback_gist_and_restore_is_active_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='course',
            name='courses_is_acti_25e634_idx',
        ),
        migrations.AlterField(
            model_name='course',
            name='registrations_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['registrations_count'], name='courses_registr_027083_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active', 'start_at', 'end_at'], name='courses_is_acti_2b8793_idx'),
        ),
    ]
