# Generated by Django 5.1.3 on 2025-09-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial_squashed_0005_remove_course_courses_is_acti_25e634_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
