# Generated by Django 5.1.3 on 2025-09-29 04:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_alter_course_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='courseregistration',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='courseregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('user', 'course'), name='uniq_active_course_registration'),
        ),
    ]
