# Generated by Django 5.1.3 on 2025-09-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_courseregistration_unique_together_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active', 'start_at'], name='courses_active_start_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['is_active', 'end_at'], name='courses_active_end_idx'),
        ),
    ]
