# Generated by Django 5.1.3 on 2025-09-29 12:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tests', '0001_squashed_0003_alter_test_end_at_alter_test_start_at'), ('tests', '0004_testregistration_attempted_at_and_more'), ('tests', '0005_remove_test_tests_is_acti_ec1450_idx_and_more'), ('tests', '0006_alter_test_registrations_count'), ('tests', '0007_alter_test_title'), ('tests', '0008_alter_testregistration_unique_together_and_more'), ('tests', '0009_remove_test_tests_is_acti_8a1432_idx_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registrations_count', models.PositiveIntegerField(default=0)),
                ('end_at', models.DateTimeField()),
                ('start_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tests',
                'indexes': [models.Index(fields=['created_at'], name='tests_created_b2a0b0_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tests.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_registrations', to=settings.AUTH_USER_MODEL)),
                ('attempted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('registered', 'registered'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('cancelled', 'cancelled')], db_index=True, default='registered', max_length=20)),
            ],
            options={
                'db_table': 'test_registrations',
                'indexes': [models.Index(fields=['test'], name='test_regist_test_id_ce02b4_idx'), models.Index(fields=['user'], name='test_regist_user_id_11e563_idx'), models.Index(fields=['status'], name='test_regist_status_da4e65_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['registrations_count'], name='tests_registr_2d3341_idx'),
        ),
        migrations.AddConstraint(
            model_name='testregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('user', 'test'), name='uniq_active_test_registration'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['is_active', 'start_at'], name='tests_active_start_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['is_active', 'end_at'], name='tests_active_end_idx'),
        ),
    ]
