# Generated by Django 5.1.3 on 2025-09-26 11:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('tests', '0001_initial'), ('tests', '0002_remove_test_description_test_end_at_test_start_at'), ('tests', '0003_alter_test_end_at_alter_test_start_at')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registrations_count', models.PositiveIntegerField(db_index=True, default=0)),
                ('end_at', models.DateTimeField()),
                ('start_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'tests',
                'indexes': [models.Index(fields=['created_at'], name='tests_created_b2a0b0_idx'), models.Index(fields=['is_active'], name='tests_is_acti_ec1450_idx')],
            },
        ),
        migrations.CreateModel(
            name='TestRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tests.test')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_registrations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'test_registrations',
                'indexes': [models.Index(fields=['test'], name='test_regist_test_id_ce02b4_idx'), models.Index(fields=['user'], name='test_regist_user_id_11e563_idx')],
                'unique_together': {('user', 'test')},
            },
        ),
    ]
