# Generated by Django 5.1.3 on 2025-09-26 12:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_squashed_0003_alter_test_end_at_alter_test_start_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testregistration',
            name='attempted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='testregistration',
            name='status',
            field=models.CharField(choices=[('registered', 'registered'), ('in_progress', 'in_progress'), ('completed', 'completed'), ('cancelled', 'cancelled')], db_index=True, default='registered', max_length=20),
        ),
        migrations.AddIndex(
            model_name='testregistration',
            index=models.Index(fields=['status'], name='test_regist_status_da4e65_idx'),
        ),
    ]
