# Generated by Django 5.1.3 on 2025-09-28 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_testregistration_attempted_at_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='test',
            name='tests_is_acti_ec1450_idx',
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['registrations_count'], name='tests_registr_2d3341_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['is_active', 'start_at', 'end_at'], name='tests_is_acti_8a1432_idx'),
        ),
    ]
