# Generated by Django 5.1.3 on 2025-09-28 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_remove_test_tests_is_acti_ec1450_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='registrations_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
