# Generated by Django 5.1.3 on 2025-09-29 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0006_alter_test_registrations_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
