# Generated by Django 5.1.3 on 2025-09-29 04:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_alter_test_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='testregistration',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='testregistration',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'cancelled'), _negated=True), fields=('user', 'test'), name='uniq_active_test_registration'),
        ),
    ]
