# Generated by Django 5.1.3 on 2025-09-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0008_alter_testregistration_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='test',
            name='tests_is_acti_8a1432_idx',
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['is_active', 'start_at'], name='tests_active_start_idx'),
        ),
        migrations.AddIndex(
            model_name='test',
            index=models.Index(fields=['is_active', 'end_at'], name='tests_active_end_idx'),
        ),
    ]
